FROM golang:alpine AS development

ENV GOPATH=/go/

RUN apk add --no-cache \
    git \
    iw \
    gawk \
    curl \
    gcc \
    musl-dev \
    npm \
    python \
    make \
    g++

WORKDIR /go/src/wazigate-system/
ENTRYPOINT ["tail", "-f", "/dev/null"]

# sudo docker exec -it $CNT sh
# go build -o /build/wazigate-system -i /go/src/wazigate-system/

# npm run build
# npm i jquery popper.js bootstrap
# npm i react-bootstrap
# npm i react-bootstrap bootstrap