FROM alpine:latest AS development

ENV GOPATH=/go/

RUN apk add --no-cache \
    go \
    git \
    iw \
    gawk \
    curl \
    gcc \
    musl-dev \
    npm \
    python \
    make \
    g++

WORKDIR /go/src/wazigate-system/
ENTRYPOINT ["tail", "-f", "/dev/null"]