version: "3.4"
services:
  wazigate-system:
    image: waziup/wazigate-system:latest
    container_name: waziup.wazigate-system
    build:
      context: ./
    volumes:
      - ./:/root/app
      - ./resolv.conf:/etc/resolv.conf
      - /var/run:/var/run
      # - /var/run/dbus:/var/run/dbus
      - /sys/class/gpio:/sys/class/gpio
      - /dev/mem:/dev/mem
      - ./:/go/src/github.com/Waziup/wazigate-system
      - /etc/NetworkManager:/etc/NetworkManager
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /sys/class/net:/sys/class/net:ro
    privileged: true
    network_mode: host
    environment:
      - DEBUG_MODE=1
    healthcheck:
      test: curl --fail --unix-socket /root/app/proxy.sock http://localhost/ || exit 1
      interval: 30s
      retries: 10 # Will try for 5 minutes      
    restart: always
    security_opt:
      - "seccomp:unconfined"
