// Code generated by "stringer -type=DeviceStateReason -trimprefix=DeviceStateReason"; DO NOT EDIT.

package nm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeviceStateReasonNone-0]
	_ = x[DeviceStateReasonUnknown-1]
	_ = x[DeviceStateReasonNowManaged-2]
	_ = x[DeviceStateReasonNowUnmanaged-3]
	_ = x[DeviceStateReasonConfigFailed-4]
	_ = x[DeviceStateReasonIpConfigUnavailable-5]
	_ = x[DeviceStateReasonIpConfigExpired-6]
	_ = x[DeviceStateReasonNoSecrets-7]
	_ = x[DeviceStateReasonSupplicantDisconnect-8]
	_ = x[DeviceStateReasonSupplicantConfigFailed-9]
	_ = x[DeviceStateReasonSupplicantFailed-10]
	_ = x[DeviceStateReasonSupplicantTimeout-11]
	_ = x[DeviceStateReasonPppStartFailed-12]
	_ = x[DeviceStateReasonPppDisconnect-13]
	_ = x[DeviceStateReasonPppFailed-14]
	_ = x[DeviceStateReasonDhcpStartFailed-15]
	_ = x[DeviceStateReasonDhcpError-16]
	_ = x[DeviceStateReasonDhcpFailed-17]
	_ = x[DeviceStateReasonSharedStartFailed-18]
	_ = x[DeviceStateReasonSharedFailed-19]
	_ = x[DeviceStateReasonAutoipStartFailed-20]
	_ = x[DeviceStateReasonAutoipError-21]
	_ = x[DeviceStateReasonAutoipFailed-22]
	_ = x[DeviceStateReasonModemBusy-23]
	_ = x[DeviceStateReasonModemNoDialTone-24]
	_ = x[DeviceStateReasonModemNoCarrier-25]
	_ = x[DeviceStateReasonModemDialTimeout-26]
	_ = x[DeviceStateReasonModemDialFailed-27]
	_ = x[DeviceStateReasonModemInitFailed-28]
	_ = x[DeviceStateReasonGsmApnFailed-29]
	_ = x[DeviceStateReasonGsmRegistrationNotSearching-30]
	_ = x[DeviceStateReasonGsmRegistrationDenied-31]
	_ = x[DeviceStateReasonGsmRegistrationTimeout-32]
	_ = x[DeviceStateReasonGsmRegistrationFailed-33]
	_ = x[DeviceStateReasonGsmPinCheckFailed-34]
	_ = x[DeviceStateReasonFirmwareMissing-35]
	_ = x[DeviceStateReasonRemoved-36]
	_ = x[DeviceStateReasonSleeping-37]
	_ = x[DeviceStateReasonConnectionRemoved-38]
	_ = x[DeviceStateReasonUserRequested-39]
	_ = x[DeviceStateReasonCarrier-40]
	_ = x[DeviceStateReasonConnectionAssumed-41]
	_ = x[DeviceStateReasonSupplicantAvailable-42]
	_ = x[DeviceStateReasonModemNotFound-43]
	_ = x[DeviceStateReasonBtFailed-44]
	_ = x[DeviceStateReasonGsmSimNotInserted-45]
	_ = x[DeviceStateReasonGsmSimPinRequired-46]
	_ = x[DeviceStateReasonGsmSimPukRequired-47]
	_ = x[DeviceStateReasonGsmSimWrong-48]
	_ = x[DeviceStateReasonInfinibandMode-49]
	_ = x[DeviceStateReasonDependencyFailed-50]
	_ = x[DeviceStateReasonBr2684Failed-51]
	_ = x[DeviceStateReasonModemManagerUnavailable-52]
	_ = x[DeviceStateReasonSsidNotFound-53]
	_ = x[DeviceStateReasonSecondaryConnectionFailed-54]
	_ = x[DeviceStateReasonDcbFcoeFailed-55]
	_ = x[DeviceStateReasonTeamdControlFailed-56]
	_ = x[DeviceStateReasonModemFailed-57]
	_ = x[DeviceStateReasonModemAvailable-58]
	_ = x[DeviceStateReasonSimPinIncorrect-59]
	_ = x[DeviceStateReasonNewActivation-60]
	_ = x[DeviceStateReasonParentChanged-61]
	_ = x[DeviceStateReasonParentManagedChanged-62]
	_ = x[DeviceStateReasonOvsdbFailed-63]
	_ = x[DeviceStateReasonIpAddressDuplicate-64]
	_ = x[DeviceStateReasonIpMethodUnsupported-65]
	_ = x[DeviceStateReasonSriovConfigurationFailed-66]
	_ = x[DeviceStateReasonPeerNotFound-67]
}

const _DeviceStateReason_name = "NoneUnknownNowManagedNowUnmanagedConfigFailedIpConfigUnavailableIpConfigExpiredNoSecretsSupplicantDisconnectSupplicantConfigFailedSupplicantFailedSupplicantTimeoutPppStartFailedPppDisconnectPppFailedDhcpStartFailedDhcpErrorDhcpFailedSharedStartFailedSharedFailedAutoipStartFailedAutoipErrorAutoipFailedModemBusyModemNoDialToneModemNoCarrierModemDialTimeoutModemDialFailedModemInitFailedGsmApnFailedGsmRegistrationNotSearchingGsmRegistrationDeniedGsmRegistrationTimeoutGsmRegistrationFailedGsmPinCheckFailedFirmwareMissingRemovedSleepingConnectionRemovedUserRequestedCarrierConnectionAssumedSupplicantAvailableModemNotFoundBtFailedGsmSimNotInsertedGsmSimPinRequiredGsmSimPukRequiredGsmSimWrongInfinibandModeDependencyFailedBr2684FailedModemManagerUnavailableSsidNotFoundSecondaryConnectionFailedDcbFcoeFailedTeamdControlFailedModemFailedModemAvailableSimPinIncorrectNewActivationParentChangedParentManagedChangedOvsdbFailedIpAddressDuplicateIpMethodUnsupportedSriovConfigurationFailedPeerNotFound"

var _DeviceStateReason_index = [...]uint16{0, 4, 11, 21, 33, 45, 64, 79, 88, 108, 130, 146, 163, 177, 190, 199, 214, 223, 233, 250, 262, 279, 290, 302, 311, 326, 340, 356, 371, 386, 398, 425, 446, 468, 489, 506, 521, 528, 536, 553, 566, 573, 590, 609, 622, 630, 647, 664, 681, 692, 706, 722, 734, 757, 769, 794, 807, 825, 836, 850, 865, 878, 891, 911, 922, 940, 959, 983, 995}

func (i DeviceStateReason) String() string {
	if i >= DeviceStateReason(len(_DeviceStateReason_index)-1) {
		return "DeviceStateReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceStateReason_name[_DeviceStateReason_index[i]:_DeviceStateReason_index[i+1]]
}
