const path = require("path");
const package = require("./package.json");
const fs = require("fs");
const childProcess = require("child_process");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const { merge } = require("webpack-merge");
const webpack = require("webpack");

var branch = "unknown";
try {
	branch = childProcess.execSync("git rev-parse --abbrev-ref HEAD", {
		encoding: "utf8"
	});
	branch = branch.trim();
} catch (err) { }

const version = package.version;

console.log("This is a %s build. %s", branch, version);

fs.writeFileSync(
	"./src/version.ts",
	`
// Autogenerated by webpack.config.js
export const version = "${version}";
export const branch = "${branch}";
`
);

const common = {

	resolve: {
		extensions: [".ts", ".tsx", ".scss", ".css", ".js"],
		fallback: {
			buffer: require.resolve('buffer/'),
			url: require.resolve('url'),
			util: require.resolve("util")
		},
		alias: {
			process: "process/browser"
		},
	},

	entry: [`./src/index.tsx`],

	plugins: [
		new MiniCssExtractPlugin({
			filename: `index.css`,
		}),
		new webpack.ProvidePlugin({
			Buffer: ['buffer', 'Buffer'],
			process: 'process/browser',
		}),
	],

	module: {
		rules: [
			{
				test: /\.ts(x?)$/,
				exclude: /node_modules/,
				use: "ts-loader"
			},
			{
				test: /\.(s?)css$/,
				use: [MiniCssExtractPlugin.loader, "css-loader", "sass-loader"],
				// exclude: /node_modules/
			},
			{
				test: /\.(otf|ttf|woff|woff2|eot)$/,
				type: 'asset/resource',
			},
			{
				test: /\.(png|svg|jpg|gif)$/,
				loader: "file-loader",
				options: {
					publicPath: "img",
					outputPath: "img"
				}
			},
			{
				enforce: "pre",
				test: /\.js$/,
				loader: "source-map-loader"
			},
			{
				test: /\.less$/,
				use: [
					{
						loader: "style-loader", // creates style nodes from JS strings
					},
					{
						loader: "css-loader", // translates CSS into CommonJS
					},
					{
						loader: "less-loader", // compiles Less to CSS
					},
				],
			}
		]
	},

	output: {
		filename: "index.js",
		path: path.resolve(__dirname, "dist")
	},

	externals: [
		{
			react: "React",
			"react-dom": "ReactDOM",
		},
	]
};

module.exports = (env) => {
	console.log(env);
	if (env.dev) {
		return merge(common, {
			mode: "development",
			devtool: "eval-source-map",
		});
	}

	return merge(common, {
		mode: "production",
	});
}

